[package]
name = "hirust-mapper-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "hirust-mapper ORM 运行时：session、executor、配置、热重载"

[dependencies]
hirust-mapper-core = { path = "../hirust-mapper-core" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
glob = { workspace = true }
toml = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio", "any"] }
tokio = { workspace = true }

[features]
default = ["sqlite"]
# 数据库后端 feature gates
mysql = ["sqlx/mysql"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]
