[package]
name = "hirust-mapper-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../README.md"
description = "MyBatis XML 动态 SQL 解析与生成核心库"
keywords = ["mybatis", "sql", "xml", "dynamic-sql", "parser"]
categories = ["database", "parser-implementations"]

[dependencies]
quick-xml = "0.38"
serde_json = "1"
regex = "1"
lazy_static = "1.5"
